name: randomseat

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17을 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: directory check
        run: |
          pwd

      - name: create & grand permission pemkey
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: ssh to ec2
        run: |
          ssh -ti private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}
          cd /home/${{ secrets.EC2_USERNAME }}

      - name: install java
        run: |
          wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - 
          sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
          sudo apt-get update; sudo apt-get install -y java-17-amazon-corretto-jdk

      - name: git clone & checkout
        run: |
          git clone https://github.com/pricelees/2024-mouda-randomseat.git
          cd 2024-mouda-randomseat
          git checkout dev

      - name: gradlew build
        run: |
          chmod u+x gradlew
          ./gradlew clean build -x test

      - name: deploy
        run: |
          cd build/libs
          nohup java -jar randomseat-0.0.1-SNAPSHOT.jar &
          




#      - name: Create private key file
#        run: sudo echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
#
#      - name: Change permission of the private key
#        run: chmod 600 private_key.pem
#
#      - name: Run deployment script
#        run: |
#          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
#            cd /home/${{ secrets.EC2_USERNAME }}
#            if [ ! -d "2024-mouda-randomseat" ]; then
#              git clone https://github.com/pricelees/2024-mouda-randomseat.git
#            else
#              cd 2024-mouda-randomseat
#              git pull
#            fi
#            cd 2024-mouda-randomseat
#            chmod 777 deploy.sh
#            ./deploy.sh
#          EOF
#
#      - name: Clean up
#        run: rm -f private_key.pem
